name = "SatelliteToolboxCelestialBodies"
uuid = "b0edd99f-a7ca-4aa6-9a1e-a53e8f506046"
license = "MIT"
desc = "General functions related to celestial bodies for the SatelliteToolbox.jl ecosystem"
authors = ["Ronan Arraes Jardim Chagas <ronisbr@gmail.com>"]
version = "0.1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SatelliteToolboxBase = "9e17983a-0463-41a7-9a16-1682db6d8b66"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
Reexport = "1"
SatelliteToolboxBase = "0.2.1, 0.3"
StaticArrays = "1"
julia = "1.6"

[extras]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
ReferenceFrameRotations = "74f56ac7-18b3-5285-802d-d4bd4f104033"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "LinearAlgebra", "ReferenceFrameRotations"]
